vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        badge:
            uri_prefix: /pictures/uploads/badge
            upload_destination: '%kernel.project_dir%/public/pictures/uploads/badge'
            namer: 
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'imageSlug' } 

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
        project:
            uri_prefix: /pictures/uploads/project
            upload_destination: '%kernel.project_dir%/public/pictures/uploads/project'
            namer: 
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'imageSlug' } 

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
